# Project Configuration
group = org.eclipse.keypop
title = Keypop Card API
description = API dedicated to card extension development
version = 3.0.0-SNAPSHOT

# Java Configuration
javaSourceLevel = 1.8
javaTargetLevel = 1.8

# UTF-8 required by javadoc for special characters (ex. copyright) with Java 11+
org.gradle.jvmargs = "-Dfile.encoding=UTF-8"

# Documentation Configuration
javadoc.logo = <a target="_parent" href="https://keypop.org/"><img src="https://keypop.org/media/logo-bg-white.svg" height="20px" style="background-color: white; padding: 3px; margin: 0 10px -7px 3px;"/></a>
javadoc.copyright = Copyright &copy; Eclipse Foundation, Inc. All Rights Reserved.

# Project URLs
project.url = https://github.com/eclipse-keypop/keypop-card-java-api

# Organization
organization.name = Eclipse Keypop
organization.url = https://keypop.org/

# License
license.name = MIT license
license.url = https://opensource.org/license/mit/
license.distribution = repo

# Developers
developer.name = Keypop Contributors
developer.email = keypop-dev@eclipse.org

# Source Control Management
scm.connection = scm:git:git://github.com/eclipse-keypop/keypop-card-java-api.git
scm.developerConnection = scm:git:https://github.com/eclipse-keypop/keypop-card-java-api.git
scm.url = https://github.com/eclipse-keypop/keypop-card-java-api

# Continuous Integration
ci.system = GitHub Actions
ci.url = https://github.com/eclipse-keypop/keypop-card-java-api/actions
