name: Check Doc Updates and Trigger Documentation Update

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

permissions:
  checks: write

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      has-token: ${{ steps.check.outputs.has-token }}
    steps:
      - id: check
        run: |
          if [ "${{ secrets.ORG_GITHUB_BOT_TOKEN }}" != "" ]; then
            echo "has-token=true" >> "$GITHUB_OUTPUT"
          else
            echo "has-token=false" >> "$GITHUB_OUTPUT"
          fi

  check-and-notify:
    needs: check-secret
    if: needs.check-secret.outputs.has-token == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check last commit time
        id: check-updates
        run: |
          RESPONSE=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/commits/doc")
          
          LAST_COMMIT_DATE=$(echo $RESPONSE | jq -r '.commit.author.date')
          LAST_COMMIT_TIME=$(date -d "$LAST_COMMIT_DATE" +%s)
          CURRENT_TIME=$(date +%s)
          
          TIME_DIFF=$((CURRENT_TIME - LAST_COMMIT_TIME))
          
          if [ $TIME_DIFF -le 3600 ]; then
            echo "Recent changes found (less than 1 hour old)"
            echo "Time difference (seconds): $TIME_DIFF"
            echo "should-update=true" >> "$GITHUB_OUTPUT"
          else
            echo "No recent changes"
            echo "should-update=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Repository Dispatch Event
        if: steps.check-updates.outputs.should-update == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ORG_GITHUB_BOT_TOKEN }}
          repository: eclipse-keypop/keypop-api-docs
          event-type: update-submodules